### PR TITLE
fix `AddLog` unmarshaling tx

### LINKED ISSUE #187: `AddLog` failed when unmarshaling tx
__System info:__ ethermint main branch

__Steps to reproduce:__

The (one of the) root cause of https://github.com/tharsis/ethermint/issues/139 is [unmarshal tx failed](https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/statedb.go#L576), since the txbytes is the wrapping cosmos tx not the ethereum msg.
But we don't have a txDecoder here.

### PR DESCRIPTION
**Pull request by yihuang**
Closes #187

Verified in external integration test.

## Description

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: x/evm/keeper/statedb.go [hunk 1]
```diff
@@ -572,20 +572,10 @@ func (k *Keeper) AddLog(log *ethtypes.Log) {
...
 
 	if len(k.ctx.TxBytes()) > 0 {
-		tx := &ethtypes.Transaction{}
-		if err := tx.UnmarshalBinary(k.ctx.TxBytes()); err != nil {
-			k.Logger(k.ctx).Error(
-				"ethereum tx unmarshaling failed",
-				"error", err,
-			)
-			return
-		}
```
Comment (fedekunze) [inline x/evm/keeper/statedb.go:582]: this should be the same logic as the encoding config, can you check why is it failing? is it because the `TxBytes` are different or because they are always empty?

File: x/evm/keeper/keeper.go [hunk 2]
```diff
@@ -36,7 +36,11 @@ type Keeper struct {
 	bankKeeper    types.BankKeeper
 	stakingKeeper types.StakingKeeper
 
+	// Store current context, only works in sequential execution
 	ctx sdk.Context
+	// Store current eth tx, used by `StateDb` methods during execution of `ApplyTransaction`
+	currentTx *ethtypes.Transaction
```
Comment (fedekunze) [inline x/evm/keeper/keeper.go:42]: I'd like to identify the core issue instead of storing the tx locally on a variable when possible

File: x/evm/keeper/statedb.go (hunk 1 above)
Comment (yihuang) [reply x/evm/keeper/statedb.go]: I think the `TxBytes` is serialized form of [`sdk.Tx`](https://github.com/cosmos/cosmos-sdk/blob/e17be874bb0e3a246b74752e9b8894855cab9b03/types/tx/tx.pb.go#L32), rather than the `MsgEthereumTx`.

File: x/evm/keeper/keeper.go (hunk 2 above)
Comment (yihuang) [reply x/evm/keeper/keeper.go]: I just pushed a version that store `txDecoder`, which is better than this I think.

File: x/evm/keeper/statedb.go [hunk 3]
```diff
@@ -572,20 +572,20 @@ func (k *Keeper) AddLog(log *ethtypes.Log) {
...
-			k.Logger(k.ctx).Error(
-				"ethereum tx unmarshaling failed",
-				"error", err,
-			)
-			return
+		tx, err := k.txDecoder(k.ctx.TxBytes())
+		if err != nil {
+			panic(err)
+		}
+		ethTx, ok := tx.GetMsgs()[0].(*types.MsgEthereumTx)
```
Comment (fedekunze) [inline x/evm/keeper/statedb.go:579]: should we do a safety check for the len?

File: x/evm/keeper/statedb.go [hunk 4]
```diff
@@ -572,20 +572,20 @@ func (k *Keeper) AddLog(log *ethtypes.Log) {
...
+		if !ok {
+			panic("invalid ethereum tx")
```
Comment (fedekunze) [inline x/evm/keeper/statedb.go:581]: unsure if we should panic here or just log and return. What do you think?

**Review by fedekunze — APPROVED** [review]
Looks good. Can you add an additional test case?

File: x/evm/keeper/statedb.go (hunk 4 above)
Comment (yihuang) [reply x/evm/keeper/statedb.go:581]: These invariants should be checked already in ante handlers, log and return could end up with a broken state, panic is better I think.

Comment (yihuang) [reply x/evm/keeper/statedb.go:581]: And we only have to calculate the tm hash because of hash inconsistency issue, right? So after that one is solved, it can be simplified here.

**Comment by yihuang** [comment]
> Looks good. Can you add an additional test case?

I'm not sure how to test this in unit tests.

**Comment by fedekunze** [comment]
> I'm not sure how to test this in unit tests, should we call a contract and check logs are not empty?

On the unit test, you will have to pass invalid bytes to that the unmarshaling panics

**Comment by yihuang** [comment]
> > I'm not sure how to test this in unit tests, should we call a contract and check logs are not empty?
> 
> On the unit test, you will have to pass invalid bytes to that the unmarshaling panics

Do we have to check `len(k.ctx.TxBytes()) > 0`, I think it should be guaranteed?

**Comment by yihuang** [comment]
> > I'm not sure how to test this in unit tests, should we call a contract and check logs are not empty?
> 
> On the unit test, you will have to pass invalid bytes to that the unmarshaling panics

I changed the AddLog unit test to use a cosmos tx now.

File: x/evm/keeper/statedb.go [hunk 5]
```diff
@@ -568,25 +568,19 @@ func (k *Keeper) RevertToSnapshot(_ int) {}
...
-		}
-
-		// NOTE: we set up the transaction hash from tendermint as it is the format expected by the application:
-		// Remove once hashing is fixed on Tendermint. See https://github.com/tendermint/tendermint/issues/6539
-		key = common.BytesToHash(tmtypes.Tx(k.ctx.TxBytes()).Hash())
-
-		log.TxHash = tx.Hash()
+	tx, err := k.txDecoder(k.ctx.TxBytes())
+	if err != nil {
+		panic(err)
```
Comment (fedekunze) [inline x/evm/keeper/statedb.go:573]:
```suggestion
		// safety check, should be checked when processing the tx
		panic(err)
```

File: x/evm/keeper/statedb.go [hunk 6]
```diff
@@ -568,25 +568,19 @@ func (k *Keeper) RevertToSnapshot(_ int) {}
...
 	}
+	ethTx, ok := tx.GetMsgs()[0].(*types.MsgEthereumTx)
```
Comment (fedekunze) [inline x/evm/keeper/statedb.go:575]:
```suggestion
	// NOTE: tx length checked on AnteHandler
	ethTx, ok := tx.GetMsgs()[0].(*types.MsgEthereumTx)
```
