### PR TITLE
Problem: Missing debug_tranceBlockByHash RPC method and debug_traceBlock* may crash on non-existing block

### LINKED ISSUE #742: Problem: Missing debug_tranceBlockByHash RPC method

### LINKED ISSUE #744: Problem: debug_traceBlockByNumber crashed when block height not found
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. Call `debug_traceBlockByNumber` with an unexisting block height
2. JSON RPC returns
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```
3. Log returns
```
t=2021-11-11T14:32:45+0800 lvl=eror msg="RPC method debug_traceBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference\ngoroutine 2450 [running]:\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc002c9cc48, 0x18, 0xc001835d58)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/service.go:200 +0xbd\npanic(0x5b28380, 0x7175280)\n\truntime/panic.go:965 +0x1b9\ngithub.com/tharsis/ethermint/rpc/ethereum/namespaces/debug.(*API).traceBlock(0xc0014a0700, 0x1123123, 0x0, 0x0, 0x0, 0x2, 0x40, 0x40, 0x78861d8)\n\tgithub.com/tharsis/ethermint/rpc/ethereum/namespaces/debug/api.go:204 +0x3a\ngithub.com/tharsis/ethermint/rpc/ethereum/namespaces/debug.(*API).TraceBlockByNumber(0xc0014a0700, 0x1123123, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\tgithub.com/tharsis/ethermint/rpc/ethereum/namespaces/debug/api.go:173 +0x166\nreflect.Value.call(0xc002d22000, 0xc002d1a298, 0x13, 0x5dab6b1, 0x4, 0xc004934720, 0x3, 0x4, 0xc004934738, 0xc004122660, ...)\n\treflect/value.go:476 +0x8e7\nreflect.Value.Call(0xc002d22000, 0xc002d1a298, 0x13, 0xc004934720, 0x3, 0x4, 0x0, 0x0, 0x5b612a0)\n\treflect/value.go:337 +0xb9\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call(0xc002d202a0, 0x635f270, 0xc002cdb980, 0xc002c9cc48, 0x18, 0xc004122660, 0x2, 0x2, 0x0, 0x0, ...)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/service.go:206 +0x2c5\ngithub.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc000fddcb0, 0x635f270, 0xc002cdb980, 0xc00078aa10, 0xc002d202a0, 0xc004122660, 0x2, 0x2, 0x2)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:389 +0x8a\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc000fddcb0, 0xc004122600, 0xc00078aa10, 0x203001)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:337 +0x265\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc000fddcb0, 0xc004122600, 0xc00078aa10, 0x6340001)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:298 +0x1be\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc004122600)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:139 +0x46\ngithub.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc000fddcb0, 0xc00353a4b0)\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:226 +0xd2\ncreated by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc\n\tgithub.com/ethereum/go-ethereum@v1.10.11/rpc/handler.go:222 +0x66\n"
t=2021-11-11T14:32:45+0800 lvl=warn msg="Served debug_traceBlockByNumber" conn=[::1]:59797 reqid=1                t=2.347798ms               err="method handler crashed"
t=2021-11-11T14:32:46+0800 lvl=dbug msg="Served net_version"              conn=[::1]:59795 reqid=3944931663       t="23.27µs"
2:32PM INF Timed out dur=4891.172 height=156 module=consensus round=0 server=node step=1

```

__Expected behavior:__ [What you expected to happen]

- It should return "block not found" in JSON RPC response and should not crash.

__Actual behavior:__ [What actually happened]

Stated above

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by calvinaco**
Closes #742 and closes #744

## Description

Add the missing method

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: init.sh [hunk 1]
```diff
@@ -14,77 +14,77 @@ TRACE="--trace"
...
-# Collect genesis tx
-ethermintd collect-gentxs
-
-# Run this to ensure everything worked and that the genesis file is setup correctly
-ethermintd validate-genesis
-
-if [[ $1 == "pending" ]]; then
-  echo "pending mode is on, please wait for the first block committed."
-fi
+#ethermintd config keyring-backend $KEYRING
```
Comment (fedekunze) [inline init.sh:21]: can you undo the comments?

File: rpc/ethereum/namespaces/debug/api.go [hunk 2]
```diff
@@ -167,12 +167,37 @@ func (a *API) TraceBlockByNumber(height rpctypes.BlockNumber, config *evmtypes.T
...
+	if resBlock == nil {
+		a.logger.Debug("block not found", "hash", hash.Hex())
+		return nil, errors.New("block not found")
+	}
+
+	if resBlock.Block == nil {
+		a.logger.Debug("block not found", "hash", hash.Hex())
+		return nil, errors.New("block not found")
+	}
+
```
Comment (fedekunze) [inline rpc/ethereum/namespaces/debug/api.go:197]:
```suggestion
```

File: rpc/ethereum/namespaces/debug/api.go [hunk 3]
```diff
@@ -167,12 +167,37 @@ func (a *API) TraceBlockByNumber(height rpctypes.BlockNumber, config *evmtypes.T
...
+func (a *API) TraceBlockByHash(hash common.Hash, config *evmtypes.TraceConfig) ([]*evmtypes.TxTraceResult, error) {
+	a.logger.Debug("debug_traceBlockByHash", "hash", hash)
+	// Get Tendermint Block
+	resBlock, err := a.backend.GetTendermintBlockByHash(hash)
+	if err != nil {
+		a.logger.Debug("get block failed", "hash", hash.Hex(), "error", err.Error())
+		return nil, err
+	}
+
+	if resBlock == nil {
```
Comment (fedekunze) [inline rpc/ethereum/namespaces/debug/api.go:188]:
```suggestion
	if resBlock == nil || resBlock.Block == nil {
```

File: rpc/ethereum/backend/backend.go [hunk 4]
```diff
@@ -306,6 +307,21 @@ func (e *EVMBackend) GetTendermintBlockByNumber(blockNum types.BlockNumber) (*tm
...
 }
 
+// GetTendermintBlockByHash returns a Tendermint format block by block number
+func (e *EVMBackend) GetTendermintBlockByHash(blockHash common.Hash) (*tmrpctypes.ResultBlock, error) {
+	resBlock, err := e.clientCtx.Client.BlockByHash(e.ctx, blockHash.Bytes())
+	if err != nil {
+		e.logger.Debug("tendermint client failed to get block", "blockHash", blockHash.Hex(), "error", err.Error())
+	}
+
+	if resBlock.Block == nil {
```
Comment (fedekunze) [inline rpc/ethereum/backend/backend.go:317]:
```suggestion
	if resBlock || resBlock.Block == nil {
```

**Review by fedekunze — APPROVED** [review]

File: rpc/ethereum/backend/backend.go [hunk 5]
```diff
@@ -306,6 +307,21 @@ func (e *EVMBackend) GetTendermintBlockByNumber(blockNum types.BlockNumber) (*tm
...
 }
 
+// GetTendermintBlockByHash returns a Tendermint format block by block number
+func (e *EVMBackend) GetTendermintBlockByHash(blockHash common.Hash) (*tmrpctypes.ResultBlock, error) {
+	resBlock, err := e.clientCtx.Client.BlockByHash(e.ctx, blockHash.Bytes())
+	if err != nil {
+		e.logger.Debug("tendermint client failed to get block", "blockHash", blockHash.Hex(), "error", err.Error())
+	}
+
+	if resBlock || resBlock.Block == nil {
```
Comment (fedekunze) [inline rpc/ethereum/backend/backend.go:317]:
```suggestion
	if resBlock == nil || resBlock.Block == nil {
```
```suggestion
	if resBlock || resBlock.Block == nil {
```
