### PR TITLE
do binary search to estimate gas

### LINKED ISSUE #268: gas estimation is not accurate
__System info:__ ethermint main branch

__Steps to reproduce:__

1. set tx gas to the value returned by estimateGas api
2. execute tx, run out of gas

__Expected behavior:__ should just work

__Actual behavior:__ run out of gas

__Additional info:__ 

Might have to do a binary search like [go-ethereum](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L963).

Because the gasUsed returned by `EthCall` is not the peak gas needed during execution, due to different kinds of gas refund.

### PR DESCRIPTION
**Pull request by yihuang**
Closes #268

part of it is extracted into https://github.com/tharsis/ethermint/pull/276.

## Description

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by fedekunze** [comment]
Let's split the binary search logic from the changes in the response. Also if you could add a test suite for the binary search because it's quite critical in the state transition logic

**Comment by leejw51crypto** [comment]
still , default gas is not working
i will check further

**Comment by leejw51crypto** [comment]
Msg Gas 401130  intrinsicGas  77768
ApplyMessage ConsumedGas 323362  UsedGas  401130

**Comment by yihuang** [comment]
- rebased on https://github.com/tharsis/ethermint/pull/276.
- moved binary search logic into rpc api, otherwise, not easy to create clean ctx for each run.

**Comment by yihuang** [comment]
> Msg Gas 401130 intrinsicGas 77768
> ApplyMessage ConsumedGas 323362 UsedGas 401130

In my test case, with this PR, the gas used is identical to the estimated one.

**Comment by leejw51crypto** [comment]
yes, strange
```
 failed to refund gas leftover gas to sender 0x48b212A71eBbB202F7cfD1aACee3A36FdE2Fbc51\\n --- at github.com/tharsis/ethermint/x/evm/keeper/state_transition.go:244 (Keeper.ApplyMessage) ---\\nCaused by: failed to refund 4968853 leftover gas (99377060aphoton)\\n
```

**Comment by leejw51crypto** [comment]
in ApplyMessage,
leftoverGas, err = k.RefundGas(msg, leftoverGas)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to refund gas leftover gas to sender %s", msg.From())
	}


that line fails

**Comment by yihuang** [comment]
> in ApplyMessage,
> leftoverGas, err = k.RefundGas(msg, leftoverGas)
> if err != nil {
> return nil, stacktrace.Propagate(err, "failed to refund gas leftover gas to sender %s", msg.From())
> }
> 
> that line fails

When sending tx or doing estimate gas?

**Comment by leejw51crypto** [comment]
without any gas option , not working
with gas option, working

**Comment by leejw51crypto** [comment]
server side log
```
t=2021-07-13T20:13:00+0900 lvl=warn msg="Served eth_estimateGas"           conn=127.0.0.1:59245 reqid=49 t="621.75µs"            
   err="rpc error: code = InvalidArgument desc = failed to refund gas leftover gas to sender 0x48b212A71eBbB202F7cfD1aACee3A36FdE2Fbc51\n 
--- at github.com/tharsis/ethermint/x/evm/keeper/state_transition.go:244 
(Keeper.ApplyMessage) ---\nCaused by: failed to refund 4968853
leftover gas (99377060aphoton)\n --- at github.com/tharsis/ethermint/x/evm/keeper/state_transition.go:323 
(Keeper.RefundGas) ---\nCaused by: fee collector account failed
 to refund fees: 8022600aphoton is smaller than
 99377060aphoton: insufficient funds: insufficient funds: invalid request"
```

**Comment by yihuang** [comment]
> server side log
> 
> ```
> t=2021-07-13T20:13:00+0900 lvl=warn msg
> ="Served eth_estimateGas"         
>   conn=127.0.0.1:59245 reqid=49 t="621.75µs"            
>    err="rpc error: code = InvalidArgument desc =
>  failed to refund gas leftover gas to sender 0x48b212A71eBbB202F7cfD1aAC
> ee3A36FdE2Fbc51\n 
> --- at github.com/tharsis/ethermint/x/evm
> /keeper/state_transition.go:244 
> (Keeper.ApplyMessage) ---\nCaused by:
>  failed to refund 4968853
> leftover gas (99377060aphoton)\n --- at github.com/tharsis/ethermint/x/evm/
> keeper/state_transition.go:323 
> (Keeper.RefundGas) ---\n
> Caused by: fee collector account failed
>  to refund fees: 8022600aphoton 
> is smaller than
>  99377060aphoton: insufficient funds: 
> insufficient funds: invalid request"
> ```

I think you are using a different version, judging by the line numbers in stack trace.

**Comment by leejw51crypto** [comment]
i'll fetch --all, and check again

**Comment by leejw51crypto** [comment]
confirmed working good

**Review by leejw51crypto — APPROVED** [review]
lgtm

File: ethereum/rpc/namespaces/eth/api.go [hunk 1]
```diff
@@ -541,32 +557,126 @@ func (e *PublicAPI) doCall(
...
-	if err != nil {
-		return 0, err
+	blockNr := rpctypes.EthPendingBlockNumber
+	if blockNrOptional != nil {
+		blockNr = *blockNrOptional
 	}
 
-	if data.Reverted {
-		return 0, evmtypes.NewExecErrorWithReason(data.Ret)
+	// Binary search the gas requirement, as it may be higher than the amount used
```
Comment (fedekunze) [inline ethereum/rpc/namespaces/eth/api.go:595]: can we create a separate function for the binary search so that we can test it? ideally, we can clean it up and use recursion

**Review by fedekunze — COMMENTED** [review]
Looks definitely better, see the comment about recursion. There are some conflicts that need to be resolved

File: ethereum/rpc/namespaces/eth/api.go (hunk 1 above)
Comment (yihuang) [reply ethereum/rpc/namespaces/eth/api.go:595]: done

File: ethereum/rpc/namespaces/eth/api.go [hunk 2]
```diff
@@ -538,11 +557,21 @@ func (e *PublicAPI) doCall(
 	if err != nil {
 		return nil, err
 	}
-	req := evmtypes.EthCallRequest{Args: bz}
+	req := evmtypes.EthCallRequest{Args: bz, GasCap: ethermint.DefaultRPCGasLimit}
+
+	// From ContextWithHeight: if the provided height is 0,
+	// it will return an empty context and the gRPC query will use
+	// the latest block height for querying.
```
Comment (thomas-nguy) [inline ethereum/rpc/namespaces/eth/api.go:564]: Not sure it the contextWithHeight is actually working.

Btw if the provided height is 0, shouldnt it uses the earliest block height instead? Maybe comment needs to be changed

**Review by thomas-nguy — APPROVED** [review]
overall lgtm

File: ethereum/rpc/namespaces/eth/api.go (hunk 2 above)
Comment (yihuang) [reply ethereum/rpc/namespaces/eth/api.go:564]: `blockNr.Int64()` will convert 0(earliest) -> 1, and negative numbers(pending/latest) -> 0.

File: ethereum/rpc/namespaces/eth/api.go [hunk 3]
```diff
@@ -529,6 +534,20 @@ func (e *PublicAPI) Call(args evmtypes.CallArgs, blockNr rpctypes.BlockNumber, _
...
+// isIntrinsicGasError try to reflex the error internal, to decide if it's a `core.ErrIntrinsicGas`,
+// pretty hacky
+func isIntrinsicGasError(err error) bool {
+	if se, ok := status.FromError(err); ok {
+		wrapper := status.Error(
+			codes.Internal,
+			core.ErrIntrinsicGas.Error(),
+		)
+		sdkWrapper := sdkerrors.Wrap(sdkerrors.ErrUnknownRequest, wrapper.Error())
+		return se.Message() == sdkWrapper.Error()
```
Comment (fedekunze) [inline ethereum/rpc/namespaces/eth/api.go:546]: can you use `errors.Is`?

File: x/evm/keeper/state_transition.go [hunk 4]
```diff
@@ -231,8 +231,9 @@ func (k *Keeper) ApplyMessage(evm *vm.EVM, msg core.Message, cfg *params.ChainCo
 	}
 	// Should check again even if it is checked on Ante Handler, because eth_call don't go through Ante Handler.
 	if msg.Gas() < intrinsicGas {
-		// eth_estimateGas will check for this exact error
-		return nil, stacktrace.Propagate(core.ErrIntrinsicGas, "intrinsic gas too low")
+		// eth_estimateGas will check for this exact error,
+		// don't wrap it with stacktrace, that makes it very hard to decipher for the client
+		return nil, core.ErrIntrinsicGas
```
Comment (fedekunze) [inline x/evm/keeper/state_transition.go:236]: maybe consider using `error.Is`?

Comment (yihuang) [reply x/evm/keeper/state_transition.go:236]: I think we can’t do that because it get serialized to string and transfer to the client.

File: ethereum/rpc/namespaces/eth/api.go (hunk 3 above)
Comment (yihuang) [reply ethereum/rpc/namespaces/eth/api.go:546]: No, it’s simply a string after transferred to client.

File: x/evm/keeper/state_transition.go (hunk 4 above)
Comment (yihuang) [reply x/evm/keeper/state_transition.go:236]: Actually I've tried another approach which put the binary search logic into the grpc handler, creating a `EstimateGas` grpc endpoint.

Comment (yihuang) [reply x/evm/keeper/state_transition.go]: Just done that, looks better now.

File: ethereum/rpc/namespaces/eth/api.go (hunk 3 above)
Comment (fedekunze) [reply ethereum/rpc/namespaces/eth/api.go]: what about `strings.Contains`

Comment (yihuang) [reply ethereum/rpc/namespaces/eth/api.go]: this is out dated now, current version is better

File: x/evm/keeper/state_transition.go (hunk 4 above)
Comment (fedekunze) [reply x/evm/keeper/state_transition.go]: > Actually I've tried another approach which put the binary search logic into the grpc handler, creating a EstimateGas grpc endpoint. But at that time I don't how to make each iteration run in a clean context, maybe I can try CacheContext.

I think we should be using the binary search on the client-side instead. It might not be as clean but at least we move unnecessary computation from the grpc handler. Thoughts? cc: @khoslaventures

Comment (yihuang) [reply x/evm/keeper/state_transition.go]: In a default setup both rpc apis and grpc apis are kind of server side?

Comment (yihuang) [reply x/evm/keeper/state_transition.go]: And if one set log level to info (I think that’s the default), there’s a log for each grpc query, it would be confusing if one rpc call emites several grpc query logs.

File: ethereum/rpc/namespaces/eth/api.go [hunk 5]
```diff
@@ -567,18 +577,28 @@ func (e *PublicAPI) doCall(
 }
 
 // EstimateGas returns an estimate of gas usage for the given smart contract call.
-func (e *PublicAPI) EstimateGas(args evmtypes.CallArgs) (hexutil.Uint64, error) {
+func (e *PublicAPI) EstimateGas(args evmtypes.CallArgs, blockNrOptional *rpctypes.BlockNumber) (hexutil.Uint64, error) {
```
Comment (khoslaventures) [inline ethereum/rpc/namespaces/eth/api.go:580]: This is supposed to be `blockNrOrHash *rpc.BlockNumberOrHash` right?

File: x/evm/keeper/grpc_query.go [hunk 6]
```diff
@@ -393,3 +400,100 @@ func (k Keeper) EthCall(c context.Context, req *types.EthCallRequest) (*types.Ms
...
+	ctx := sdk.UnwrapSDKContext(c)
+	k.WithContext(ctx)
+
+	var args types.CallArgs
+	err := json.Unmarshal(req.Args, &args)
+	if err != nil {
+		return nil, status.Error(codes.InvalidArgument, err.Error())
+	}
+
+	// Binary search the gas requirement, as it may be higher than the amount used
```
Comment (khoslaventures) [inline x/evm/keeper/grpc_query.go:415]: it's interesting that the binary search on geth is used by the public api side meaning it is done by the client of this grpc server.

At the moment the only relevant issue I've found is https://github.com/ethereum/go-ethereum/issues/21769

I think we should do the binary search on the public API (grpc client side) for sake of matching what they do in Geth

> one rpc call emites several grpc query logs.

But this is a reasonable pattern right? I think we can adjust the logs to make it more clear that these are part of the same process... effectively it is slow and painful to estimate gas so logging completions per call is not necessarily bad

@fedekunze also any thoughts on making these RPC server files `grpc_query.go` files `grpc_server.go` - you might have more context behind the naming but I think it's less obvious.

**Review by khoslaventures — COMMENTED** [review]
great stuff

File: ethereum/rpc/namespaces/eth/api.go (hunk 5 above)
Comment (yihuang) [reply ethereum/rpc/namespaces/eth/api.go:580]: Yeah, but in our code base, there are several other apis that use `rpctypes.BlockNumber` which is actually `BlockNumberOrHash` in go-ethereum side. Maybe we can do that together in another PR.

File: x/evm/keeper/grpc_query.go (hunk 6 above)
Comment (yihuang) [reply x/evm/keeper/grpc_query.go:415]: One thing that's less clean when doing binary search in rpc api side(or grpc client side) is checking the error type, in grpc server side, you can inspect the error type directly, in grpc client side, you have to check a sub string in the error string which might not be accurate.

Comment (khoslaventures) [reply x/evm/keeper/grpc_query.go:415]: This has to do with not being able to use `error.Is` right? Are you sure that's the case? `doCall` for example will run through a contract call and expose these error types through `vmError` in Geth, we can do this as well?

Comment (yihuang) [reply x/evm/keeper/grpc_query.go:415]: > This has to do with not being able to use `error.Is` right? Are you sure that's the case? `doCall` for example will run through a contract call and expose these error types through `vmError` in Geth, we can do this as well?

Do you mean `MsgEthereumTxResponse.VmError`? that is serialized version of [these errors](https://github.com/ethereum/go-ethereum/blob/master/core/vm/errors.go#L26), when these errors are not further wrapped, you can compare the error string as a whole. But if the error is [wrapped with stacktrace](https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/state_transition.go#L249) and [grpc sdk errors](https://github.com/tharsis/ethermint/blob/main/x/evm/keeper/grpc_query.go#L391), the best you can do in the grpc client side is `strings.Contains`.

File: x/evm/keeper/grpc_query.go [hunk 7]
```diff
@@ -393,3 +400,100 @@ func (k Keeper) EthCall(c context.Context, req *types.EthCallRequest) (*types.Ms
 
 	return res, nil
 }
+
+// EstimateGas implements eth_estimateGas rpc api.
+func (k Keeper) EstimateGas(c context.Context, req *types.EthCallRequest) (*types.EstimateGasResponse, error) {
```
Comment (fedekunze) [inline x/evm/keeper/grpc_query.go:405]: can you add tests for this on a follow-up PR?

**Review by fedekunze — APPROVED** [review]

File: x/evm/keeper/grpc_query.go (hunk 7 above)
Comment (yihuang) [reply x/evm/keeper/grpc_query.go:405]: I tried to do it, but there's so many context prepare things to do in unit test environment, I'm not sure how to do it.
1. With the default `KeeperTestSuite`, `GetCoinbaseAddress` will raise an error
2. We need to allocate some funds in genesis.
