### PR TITLE
ignore no signature error for evm transactions

### LINKED ISSUE #118: Tx signature not set
__System info:__ 

MacOs

__Steps to reproduce:__

Current transaction always fails on the 
`authante.NewValidateBasicDecorator()`

because the signature is always empty.

Should we set the signature in the builder 
```builder.SetSignature(xx)```  when building transaction ? (in doCall, Call, SendRawTransaction and SendTransaction)

__Expected behavior:__ [What you expected to happen]

Basic check pass

__Actual behavior:__ [What actually happened]

Return error "invalid signature"

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by yihuang**
fixes #118

Although my test still don't success for errors related to gas, but this change do pass the signature validation issue.

## Description

Eth transactions have signature inside the message, so it's ok to not sign at cosmos tx level.

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

File: app/ante/eth.go [hunk 1]
```diff
@@ -549,3 +549,25 @@ func (issd EthIncrementSenderSequenceDecorator) AnteHandle(ctx sdk.Context, tx s
...
+	return EthValidateBasicDecorator{}
+}
+
+func (vbd EthValidateBasicDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (sdk.Context, error) {
+	// no need to validate basic on recheck tx, call next antehandler
+	if ctx.IsReCheckTx() {
+		return next(ctx, tx, simulate)
+	}
+
+	err := tx.ValidateBasic()
```
Comment (thomas-nguy) [inline app/ante/eth.go:566]: would it makes more sense to cast to MsgEthereumTx and call validateBasic on each messages?

```
	for i, msg := range tx.GetMsgs() {
		msgEthTx, ok := msg.(*evmtypes.MsgEthereumTx)
		msgEthTx.ValidateBasic()
		
```


This will call the custom ValidateBasic defined there		
https://github.com/tharsis/ethermint/blob/main/x/evm/types/msg.go#L92

File: app/ante/eth.go [hunk 2]
```diff
@@ -549,3 +549,25 @@ func (issd EthIncrementSenderSequenceDecorator) AnteHandle(ctx sdk.Context, tx s
...
+func NewEthValidateBasicDecorator() EthValidateBasicDecorator {
+	return EthValidateBasicDecorator{}
+}
+
+func (vbd EthValidateBasicDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (sdk.Context, error) {
+	// no need to validate basic on recheck tx, call next antehandler
+	if ctx.IsReCheckTx() {
+		return next(ctx, tx, simulate)
+	}
+
```
Comment (thomas-nguy) [inline app/ante/eth.go:565]: Additionally we could also check that number of msg = 1

https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L54

I think we can delete this check in `EthSigVerificationDecorator` and put it here instead 

```
	if len(tx.GetMsgs()) != 1 {		return ctx, stacktrace.Propagate(			sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "only 1 ethereum msg supported per tx, got %d", len(tx.GetMsgs())),			"",		)	}
	
	```

File: app/ante/eth.go (hunk 1 above)
Comment (yihuang) [reply app/ante/eth.go:566]: seemingly, `msg.ValidateBasic` is called before ante handler: https://github.com/cosmos/cosmos-sdk/blob/master/baseapp/baseapp.go#L622.

File: app/ante/eth.go (hunk 2 above)
Comment (yihuang) [reply app/ante/eth.go:565]: https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L76
seemingly `EthSigVerificationDecorator` is the only handler that check and rely on this assumption, maybe other members can comment on this?

**Review by fedekunze — APPROVED** [review]
Looks good 👍 thanks!

File: app/ante/eth.go (hunk 2 above)
Comment (fedekunze) [reply app/ante/eth.go:565]: as long as it's checked on the first one, it's ok. We could support multiple msgs per tx but that would be a separate improvement

File: app/ante/eth.go [hunk 3]
```diff
@@ -549,3 +549,25 @@ func (issd EthIncrementSenderSequenceDecorator) AnteHandle(ctx sdk.Context, tx s
...
+	err := tx.ValidateBasic()
+	// ErrNoSignatures is fine with eth tx
+	if err != nil && err != sdkerrors.ErrNoSignatures {
+		return ctx, err
```
Comment (fedekunze) [inline app/ante/eth.go:569]: can you add a test for this?

**Review by fedekunze — CHANGES_REQUESTED** [review]
Just noticed that a test for the AnteHandlerDecorator is missing

**Comment by yihuang** [comment]
> Just noticed that a test for the AnteHandlerDecorator is missing

I removed the signing part from the test tx.

File: app/ante/utils_test.go [hunk 4]
```diff
@@ -91,40 +89,6 @@ func (suite *AnteTestSuite) CreateTestTx(
 	builder.SetFeeAmount(fees)
 	builder.SetGasLimit(msg.GetGas())
 
-	// First round: we gather all the signer infos. We use the "set empty
```
Comment (fedekunze) [inline app/ante/utils_test.go:94]: we should provide a bool to the function if we want to sign with the Cosmos format and adapt the tests to work with both cases

File: app/ante/eth.go (hunk 3 above)
Comment (yihuang) [reply app/ante/eth.go:571]: done

File: app/ante/utils_test.go (hunk 4 above)
Comment (yihuang) [reply app/ante/utils_test.go:101]: fixed now, the old tests are still run against signed tx, added new test case for un-signed tx.

**Review by fedekunze — APPROVED** [review]
