### PR TITLE
`SendTransaction` wrap `MsgEthereumTx` in cosmos tx

### LINKED ISSUE #160: `SendTransaction` don't wrap `MsgEthereumTx` to cosmos tx
__System info:__ ethermint main branch

__Steps to reproduce:__

1. Use `eth_SendTransaction` to send a basic tx
2. it complains "Tx must be a FeeTx"

__Expected behavior:__ success

__Actual behavior:__ error "Tx must be a FeeTx"

__Additional info:__ [Include gist of relevant config, logs, etc.]

### PR DESCRIPTION
**Pull request by yihuang**
Closes #160

## Description

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by fedekunze — APPROVED** [review]
ACK

File: ethereum/rpc/eth_api.go [hunk 1]
```diff
@@ -349,7 +349,21 @@ func (e *PublicEthAPI) SendTransaction(args rpctypes.SendTxArgs) (common.Hash, e
 		return common.Hash{}, err
 	}
 
-	tx := args.ToTransaction()
+	msg := args.ToTransaction()
+
+	if err := msg.ValidateBasic(); err != nil {
+		e.logger.Debugln("tx failed basic validation", "error", err)
```
Comment (fedekunze) [inline ethereum/rpc/eth_api.go:355]:
```suggestion
		e.logger.WithError(err).Debugln("tx failed basic validation")
```
